! Generated by cart. DO NOT EDIT
program main
    implicit none

    if (.not.run()) stop 1
contains
    function run() result(passed)
        use network_type_test, only: &
                network_type_network_construction => &
                    test_network_construction
        use garden , only: test_item_t, test_that, run_tests



        logical :: passed

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(1)

        individual_tests(1) = network_type_network_construction()
        tests = test_that(individual_tests)


        passed = run_tests(tests)

    end function
end program
